version: '3'

services:
  api.plamobi:
    build:
      context: .
      dockerfile: Dockerfile
    image: plamobi-model-simulator
    container_name: plamobi
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo
 
  mongo:
    container_name: plamobi-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api.plamobi
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email contact@plamobi.com --agree-tos --no-eff-email --staging -d api.plamobi.com  

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/views/
      o: bind

networks:
  app-network:
    driver: bridge  
